# Generated by Django 4.0.5 on 2022-08-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ormapp.emp'),
        ),
    ]
