# Generated by Django 4.0.5 on 2022-08-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_account_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc', models.IntegerField()),
                ('hsc', models.IntegerField()),
                ('grad', models.IntegerField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ormapp.emp')),
            ],
        ),
    ]
