# Generated by Django 4.0.5 on 2022-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0005_education2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('emp', models.ManyToManyField(to='ormapp.emp')),
            ],
        ),
    ]
